services:
  client:
    build: ./client
    ports:
      - "5173:5173"

  server:
    build: ./server
    ports:
      - "3000:3000" # development
      - "443:443" # production HTTPS
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    environment:
      - NODE_ENV=${NODE_ENV}