services:
  client:
    build: ./client
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000

  server:
    build: ./server
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "3000:3000" # development
      - "443:443" # production HTTPS
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    env_file:
      - ./server/.env